### ISSUE TITLE
Just a sugestion

### ISSUE THREAD

**Issue by NinjaOukie** [WayofTime/Hemomancy#1]
I like blood magic in a whole... but the altar is my favorite. please dont leave that behind in 1.7 when your making your new mod.

as a altar of power and a crafting and managing machanic i love it and simply it is a one of its kind...

**Comment by Arcaratus** [comment]
This is NOT (I repeat NOT) Blood Magic. This is Hemomancy. Read the repo titles for more information. And if you don't mind, close this.

**Comment by NinjaOukie** [comment]
Technically hemomancy is still blood magic, read the lore for more info.
then on his youtube channel Way of Time made is seem like blood magic is not coming to 1.8. therefore i lose my favorite mod. but like i said just a sugestion.

**Comment by WayofTime** [comment]
Um no, hemomancy is going to be a different mod. 

And also, I don't know where you get your information, but Blood Magic is coming to 1.8, it just wasn't being worked on then: https://github.com/wayoftime/bloodmagic/tree/bloodmagic1.8
