### ISSUE TITLE
Crash when creatning spell

### ISSUE THREAD

**Issue by LiSirNo** [WayofTime/Hemomancy#2]
crash when creating spell "touch, phisical damage" after clicking square button on the bottom of the interface

version 0.0.5

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  DCLoadingPlugin (DummyCore-2.2.189.0.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 25.03.16 12:43
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at hemomancy.client.gui.inventory.ContainerSpellTinkerer.finalizeChangesToItemStack(ContainerSpellTinkerer.java:87)
    at hemomancy.client.gui.GuiSpellTinkerer.func_146284_a(GuiSpellTinkerer.java:347)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:319)
    at hemomancy.client.gui.GuiSpellTinkerer.func_73864_a(GuiSpellTinkerer.java:313)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at hemomancy.client.gui.inventory.ContainerSpellTinkerer.finalizeChangesToItemStack(ContainerSpellTinkerer.java:87)
    at hemomancy.client.gui.GuiSpellTinkerer.func_146284_a(GuiSpellTinkerer.java:347)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:319)
    at hemomancy.client.gui.GuiSpellTinkerer.func_73864_a(GuiSpellTinkerer.java:313)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
    Screen name: hemomancy.client.gui.GuiSpellTinkerer

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Gannv'/389, l='MpServer', x=-695,50, y=4,00, z=-149,42]]
    Chunk stats: MultiplayerChunkCache: 225, 225
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: -686,00,4,00,-144,00 - World: (-686,4,-144), Chunk: (at 2,0,0 in -43,-9; contains blocks -688,0,-144 to -673,255,-129), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
    Level time: 3339 game time, 3339 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 103 total; [EntityPig['Pig'/256, l='MpServer', x=-697,78, y=4,00, z=-191,41], EntityPig['Pig'/257, l='MpServer', x=-697,91, y=4,00, z=-193,97], EntityPig['Pig'/258, l='MpServer', x=-698,50, y=4,00, z=-185,50], EntityPig['Pig'/259, l='MpServer', x=-694,50, y=4,00, z=-183,50], EntityChicken['Chicken'/260, l='MpServer', x=-700,31, y=4,00, z=-184,34], EntityChicken['Chicken'/261, l='MpServer', x=-699,50, y=4,00, z=-183,50], EntityChicken['Chicken'/262, l='MpServer', x=-697,50, y=4,00, z=-185,50], EntityRabbit['Rabbit'/263, l='MpServer', x=-702,50, y=4,00, z=-189,50], EntityRabbit['Rabbit'/264, l='MpServer', x=-688,53, y=4,00, z=-184,53], EntityRabbit['Rabbit'/265, l='MpServer', x=-695,66, y=4,00, z=-190,66], EntityRabbit['Rabbit'/266, l='MpServer', x=-693,56, y=4,00, z=-186,47], EntityChicken['Chicken'/267, l='MpServer', x=-689,31, y=4,00, z=-75,63], EntityRabbit['Rabbit'/268, l='MpServer', x=-674,50, y=4,00, z=-213,50], EntityRabbit['Rabbit'/269, l='MpServer', x=-674,06, y=4,00, z=-209,06], EntityPig['Pig'/270, l='MpServer', x=-678,50, y=4,00, z=-216,50], EntityPig['Pig'/271, l='MpServer', x=-681,50, y=4,00, z=-214,50], EntityPig['Pig'/272, l='MpServer', x=-684,03, y=4,00, z=-208,09], EntityCow['Cow'/273, l='MpServer', x=-681,00, y=4,00, z=-202,13], EntityPig['Pig'/274, l='MpServer', x=-682,50, y=4,00, z=-207,50], EntityPig['Pig'/275, l='MpServer', x=-679,50, y=4,00, z=-80,50], EntityRabbit['Rabbit'/276, l='MpServer', x=-674,66, y=4,00, z=-80,66], EntityRabbit['Rabbit'/277, l='MpServer', x=-672,66, y=4,00, z=-85,66], EntityPig['Pig'/278, l='MpServer', x=-675,50, y=4,00, z=-77,50], EntityPig['Pig'/279, l='MpServer', x=-682,50, y=4,00, z=-77,50], EntityPig['Pig'/280, l='MpServer', x=-685,44, y=4,00, z=-76,31], EntityChicken['Chicken'/281, l='MpServer', x=-676,50, y=4,00, z=-79,50], EntityChicken['Chicken'/282, l='MpServer', x=-681,50, y=4,00, z=-77,50], EntityChicken['Chicken'/283, l='MpServer', x=-685,75, y=4,00, z=-78,72], EntityRabbit['Rabbit'/299, l='MpServer', x=-669,66, y=4,00, z=-210,66], EntityCow['Cow'/300, l='MpServer', x=-671,84, y=4,00, z=-215,75], EntityCow['Cow'/301, l='MpServer', x=-669,25, y=4,00, z=-213,53], EntityCow['Cow'/302, l='MpServer', x=-671,50, y=4,00, z=-217,50], EntityRabbit['Rabbit'/303, l='MpServer', x=-669,66, y=4,00, z=-206,66], EntitySheep['Sheep'/305, l='MpServer', x=-639,38, y=4,00, z=-196,53], EntitySheep['Sheep'/306, l='MpServer', x=-653,94, y=4,00, z=-201,13], EntityHorse['Horse'/307, l='MpServer', x=-640,78, y=4,00, z=-195,91], EntitySheep['Sheep'/308, l='MpServer', x=-644,50, y=4,00, z=-190,50], EntityChicken['Chicken'/309, l='MpServer', x=-650,50, y=4,00, z=-129,50], EntityChicken['Chicken'/310, l='MpServer', x=-641,59, y=4,00, z=-138,38], EntityCow['Cow'/311, l='MpServer', x=-649,19, y=4,00, z=-133,78], EntityRabbit['Rabbit'/312, l='MpServer', x=-645,16, y=4,00, z=-119,19], EntityRabbit['Rabbit'/313, l='MpServer', x=-645,91, y=4,00, z=-115,19], EntityHorse['Donkey'/314, l='MpServer', x=-650,50, y=4,00, z=-125,50], EntityHorse['Donkey'/315, l='MpServer', x=-654,88, y=4,00, z=-122,88], EntityHorse['Donkey'/316, l='MpServer', x=-653,50, y=4,00, z=-123,50], EntityCow['Cow'/317, l='MpServer', x=-643,50, y=4,00, z=-126,50], EntityCow['Cow'/318, l='MpServer', x=-645,94, y=4,00, z=-124,44], EntityCow['Cow'/319, l='MpServer', x=-644,50, y=4,00, z=-122,50], EntityChicken['Chicken'/320, l='MpServer', x=-647,50, y=4,00, z=-125,50], EntityChicken['Chicken'/321, l='MpServer', x=-644,56, y=4,00, z=-113,75], EntityRabbit['Rabbit'/322, l='MpServer', x=-650,56, y=4,00, z=-108,47], EntityRabbit['Rabbit'/323, l='MpServer', x=-633,38, y=4,00, z=-226,91], EntitySheep['Sheep'/328, l='MpServer', x=-624,50, y=4,00, z=-221,50], EntityRabbit['Rabbit'/329, l='MpServer', x=-631,28, y=4,00, z=-228,75], EntityRabbit['Rabbit'/330, l='MpServer', x=-627,63, y=4,00, z=-213,75], EntityRabbit['Rabbit'/331, l='MpServer', x=-631,66, y=4,00, z=-221,66], EntitySheep['Sheep'/333, l='MpServer', x=-625,50, y=4,00, z=-217,50], EntitySheep['Sheep'/334, l='MpServer', x=-627,50, y=4,00, z=-217,50], EntitySheep['Sheep'/335, l='MpServer', x=-625,50, y=4,00, z=-214,50], EntityHorse['Horse'/336, l='MpServer', x=-636,50, y=4,00, z=-192,50], EntitySheep['Sheep'/337, l='MpServer', x=-639,50, y=4,00, z=-189,50], EntityHorse['Horse'/338, l='MpServer', x=-639,22, y=4,00, z=-182,09], EntityHorse['Horse'/339, l='MpServer', x=-639,50, y=4,00, z=-187,50], EntityPig['Pig'/340, l='MpServer', x=-637,50, y=4,00, z=-190,50], EntityPig['Pig'/341, l='MpServer', x=-624,97, y=4,00, z=-179,00], EntityPig['Pig'/342, l='MpServer', x=-639,94, y=4,00, z=-175,00], EntityAuraNode['Aura Node'/343, l='MpServer', x=-638,50, y=16,50, z=-165,50], EntityCow['Cow'/344, l='MpServer', x=-637,47, y=4,00, z=-113,00], EntityCow['Cow'/345, l='MpServer', x=-637,72, y=4,00, z=-114,56], EntityCow['Cow'/346, l='MpServer', x=-635,31, y=4,00, z=-112,22], EntityCow['Cow'/347, l='MpServer', x=-632,50, y=4,00, z=-116,50], EntitySheep['Sheep'/348, l='MpServer', x=-636,31, y=4,00, z=-113,59], EntitySheep['Sheep'/349, l='MpServer', x=-640,03, y=4,00, z=-115,28], EntitySheep['Sheep'/350, l='MpServer', x=-645,84, y=4,00, z=-121,28], EntitySheep['Sheep'/351, l='MpServer', x=-630,91, y=4,00, z=-109,13], EntityHorse['Horse'/353, l='MpServer', x=-627,28, y=4,00, z=-223,09], EntityPlayerSP['Gannv'/389, l='MpServer', x=-695,50, y=4,00, z=-149,42], EntityRabbit['Rabbit'/355, l='MpServer', x=-623,84, y=4,00, z=-229,50], EntitySheep['Sheep'/358, l='MpServer', x=-622,50, y=4,00, z=-221,50], EntitySheep['Sheep'/359, l='MpServer', x=-620,84, y=4,00, z=-218,53], EntitySheep['Sheep'/360, l='MpServer', x=-623,50, y=4,00, z=-219,50], EntityAuraNode['Aura Node'/225, l='MpServer', x=-815,50, y=24,50, z=-230,50], EntityAuraNode['Aura Node'/226, l='MpServer', x=-810,50, y=9,50, z=-64,50], EntityChicken['Chicken'/229, l='MpServer', x=-773,38, y=4,00, z=-139,47], EntityChicken['Chicken'/230, l='MpServer', x=-771,50, y=4,00, z=-141,50], EntityChicken['Chicken'/231, l='MpServer', x=-772,50, y=4,00, z=-138,50], EntityRabbit['Rabbit'/233, l='MpServer', x=-768,13, y=4,00, z=-138,72], EntityRabbit['Rabbit'/234, l='MpServer', x=-769,59, y=4,00, z=-138,97], EntityPig['Pig'/236, l='MpServer', x=-765,81, y=4,00, z=-110,16], EntityPig['Pig'/237, l='MpServer', x=-774,50, y=4,00, z=-118,50], EntityPig['Pig'/238, l='MpServer', x=-773,31, y=4,00, z=-114,31], EntityChicken['Chicken'/243, l='MpServer', x=-775,50, y=4,00, z=-122,50], EntityChicken['Chicken'/244, l='MpServer', x=-774,50, y=4,00, z=-120,50], EntityRabbit['Rabbit'/245, l='MpServer', x=-758,66, y=4,00, z=-147,66], EntityRabbit['Rabbit'/246, l='MpServer', x=-767,53, y=4,00, z=-154,63], EntityChicken['Chicken'/247, l='MpServer', x=-765,50, y=4,00, z=-138,50], EntityRabbit['Rabbit'/248, l='MpServer', x=-761,50, y=4,00, z=-142,50], EntityRabbit['Rabbit'/249, l='MpServer', x=-764,66, y=4,00, z=-139,66], EntityRabbit['Rabbit'/250, l='MpServer', x=-763,66, y=4,00, z=-139,66], EntityRabbit['Rabbit'/251, l='MpServer', x=-756,66, y=4,00, z=-141,66], EntityAuraNode['Aura Node'/253, l='MpServer', x=-733,50, y=76,50, z=-244,50], EntityAuraNode['Aura Node'/254, l='MpServer', x=-718,50, y=62,50, z=-60,50], EntityAuraNode['Aura Node'/255, l='MpServer', x=-697,50, y=66,50, z=-212,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1006390736 bytes (959 MB) / 1755316224 bytes (1674 MB) up to 1755316224 bytes (1674 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1724M -Xms1724M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 35 mods loaded, 35 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   CoreXU2{1} [CoreXU2](minecraft.jar) 
    UCHIJAAAA   ashenwheat{1.8.9-2.0.0.2} [Ashenwheat](ashenwheat-1.8.9-2.0.0.2.jar) 
    UCHIJAAAA   basemetals{1.6.2} [Base Metals](BaseMetals-1.6.2.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.8.9-alpha-0.0.1.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   intangible{0.0.25} [Intangible](intangible-1.8.9-0.0.25.jar) 
    UCHIJAAAA   JEI{2.28.9.176} [Just Enough Items](jei_1.8.9-2.28.9.176.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-20.jar) 
    UCHIJAAAA   Thaumcraft{5.2.4} [Thaumcraft](Thaumcraft-1.8.9-5.2.4.jar) 
    UCHIJAAAA   Botania{r1.8-299} [Botania](Botania-unofficial.r1.8-299.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   cyclopscore{0.5.2} [Cyclops Core](CyclopsCore-1.8.9-0.5.2.jar) 
    UCHIJAAAA   DummyCore{2.2.189.0.} [DummyCore](DummyCore-2.2.189.0.jar) 
    UCHIJAAAA   evilcraft{0.9.4} [EvilCraft](EvilCraft-1.8.9-0.9.4.jar) 
    UCHIJAAAA   ftfloocraft{1.8.9-0.1} [Floocraft](Floocraft-1.8.9-0.1.jar) 
    UCHIJAAAA   gravestone{1.1.3} [Gravestone](Gravestone Mod 1.1.3.jar) 
    UCHIJAAAA   Hemomancy{0.0.5} [Hemomancy](Hemomancy-0.0.5.jar) 
    UCHIJAAAA   ironbackpacks{1.8.9-2.0.5} [Iron Backpacks](IronBackpacks-1.8.9-2.0.5.jar) 
    UCHIJAAAA   JEIAddons{0.11.2.56} [Just Enough Items Addons](JEIAddons_1.8.9-0.11.2.56.jar) 
    UCHIJAAAA   magic_muffins{1.1} [Magic Muffins](MagicMuffins-1.8-1.1.jar) 
    UCHIJAAAA   mantle{1.8.9-0.9.0.jenkins97} [Mantle](Mantle-1.8.9-0.9.0.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   Morpheus{1.8.9-2.0.57} [Morpheus](Morpheus-1.8.9-2.0.57.jar) 
    UCHIJAAAA   Psi{beta-23} [Psi](Psi-beta-23.jar) 
    UCHIJAAAA   xreliquary{1.3.1.222} [Reliquary](Reliquary-1.3.1.222.jar) 
    UCHIJAAAA   Roguelike{1.4.5} [Roguelike Dungeons](RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.3.4} [Storage Drawers](StorageDrawers-1.8.9-2.3.4.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct](TConstruct-1.8.9-2.2.0b.jar) 
    UCHIJAAAA   shibeid{1.0.2} [Thaumic Potatoes](Thaumic Potatoes-1.8.9-1.0.2.jar) 
    UCHIJAAAA   thaumicbases{2.1.189.32} [Thaumic Bases](ThaumicBases-2.1.189.32.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  DummyCore.ASM.DCASMManager
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9400 GT/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerDebug (Enabled/Not Forced)

```
[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''DummyCore'
Launched Version: 1.8.9-forge1.8.9-11.15.1.1764
LWJGL: 2.9.4
OpenGL: GeForce 9400 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x AMD Athlon(tm) 64 X2 Dual Core Processor 4800+
```

**Comment by WayofTime** [comment]
That is a compiled version of the mod that is NOT maintained by me. Please consult the mod author maintaining Hemomancy.
